 eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@jkm.jiangxicheng.xyz:10001/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

 spring:
#   datasource:
#     hikari:
#       jdbc-url: jdbc:oracle:thin:@jdbctest_medium?TNS_ADMIN=${wallet.path:E:\cloud\Oracle\db}\wallet_db_capital
#     driver-class-name: oracle.jdbc.driver.OracleDriver
#     username: ADMIN
#     password: yKU41:;!WTg%+n4<=sn=acJ)hyZZp/
   application:
     name: Capital-DC-A
   profiles:
     active: ${env:dev}