 eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@jkm.jiangxicheng.xyz:10001/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

 spring:
   application:
     name: Capital-Breath-A
   profiles:
     active: ${env:dev}