spring:
  application:
    name: Capital-Breath-A[DEV]
  datasource:
    hikari:
      connection-timeout: 3000000

logging:
  level:
    org:
      jxch:
        capital:
          breath:
            a:
              mapper: trace